### PR TITLE
commit 2 of 6 microservices first: customer-manage and login 

### PR DESCRIPTION
**Pull request by alec-z**
@WillemJiang As you mentioned, the pr is limited under 1000 lines.  @MabinGo

### CODE REVIEW

**Comment by WillemJiang** [comment]
This PR is more than 112k lines of code, and I just checked the code change it's almost finished in September.   Please don't send this kind of PR here.

**Comment by chanjarster** [comment]
@alec-z Thanks, I've noticed that this PR contains many `Merge pull request` commits and commits written by other people. I suspect that you didn't use `git rebase` to make your branch clean and that makes hard to review this PR.
I suggest you follow the ways introduce in http://servicecomb.apache.org/developers/submit-codes/ and create another PR.

**Comment by WillemJiang** [comment]
As there are lots of commit merge from other's PR. Please make sure all the writer has submit the iCLA first.

**Comment by alec-z** [comment]
@WillemJiang  all of the 3 submitter have submitted the iCLA already! I have check it again.

**Comment by alec-z** [comment]
@chanjarster Yes, some of commits should be `git rebase` first.  We lack of experiences so we miss this. We will do that from now on.

**Pull request closed without merging**
