### PR TITLE
5th pr, the script dir, this the db script and docker script

### PR DESCRIPTION
**Pull request by alec-z**

### CODE REVIEW

**Comment by alec-z** [comment]
@MabinGo

**Comment by WillemJiang** [comment]
100K lines of code @alec-z I don't think it's  a good pratice to submit this kind of PR.

**Comment by WillemJiang** [comment]
Can you remove the sql files  and squashing the commit?
And there are bunch of files without Apache License header.

**Comment by alec-z** [comment]
@WillemJiang I just remove the sql files and docker file, and add Apache License header  to jmeter xml file

**Pull request closed without merging**
