### PR TITLE
upgrade samples version to 1.3.0

### PR DESCRIPTION
**Pull request by liubao68**

### CODE REVIEW

**Comment by yhs0092** [comment]
Hi, it seems only part of the samples are upgraded. What about the other samples?

**Comment by liubao68** [comment]
I just upgrade samples familiar with. Not required to upgrade all samples.

**Comment by yhs0092** [comment]
> I just upgrade samples familiar with. Not required to upgrade all samples.

OK, I get it.

**Comment by WillemJiang** [comment]
Normally we just use the maven project version in the sample, if you want to use 1.3.0 sample you can check out the code from the repo by using the tag 1.3.0.

**Comment by liubao68** [comment]
> Normally we just use the maven project version in the sample, if you want to use 1.3.0 sample you can check out the code from the repo by using the tag 1.3.0.

Sorry, I don't quite understand your suggestion. Since 1.3.0 has bean released, I want all samples use latest version, and if users download samples, they do not need to consider which version is the best choice .

**Comment by WillemJiang** [comment]
If we change the sample to use java chassis version to 1.3.0 in the master branch, which version of java-chassis should use we need do when doing the 2.0 release? 
The best solution in my mind is let the sample  to use project version which means we just keep the sample  version same with the java-chassis version.

**Comment by WillemJiang** [comment]
Sorry, I just realize it's a separated repo,  we are free to update the version of Java-Chassis.
I will mege the PR shortly.

**Pull request merged**
