### PR TITLE
CustomerManage service and UserCenter service initail version

### PR DESCRIPTION
**Pull request by 1360098430**
@WillemJiang @yhs0092 the first commit of two of micro-services: CustomerManage and UserCenter

### CODE REVIEW

**Comment by alec-z** [comment]
please merge all 4 commit to 1 "UserCenter & CustomerManage Service first commit"

**Comment by WillemJiang** [comment]
@alec-z  Do you mean rebase?

**Comment by MabinGo** [comment]
I think these 4 commits express one thing, so they can be combined into one commit.

**Comment by MabinGo** [comment]
LGTM

**Pull request merged**
